//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.event.*;

public class OptionsPanel extends JPanel {
	private static final long serialVersionUID = 1L;
	
	private JRadioButton setStartButton;
    private JRadioButton setWallsButton;
    private JRadioButton setEndButton;
    private JLabel searchAlgLabel;
    private JRadioButton aStarSearchButton;
    private JRadioButton breadthFirstSearchButton;
    private JRadioButton greedySearchButton;
    private JButton doStepButton;
    private JButton doPlayButton;
    private JButton doResetButton;
    private JLabel numberOfStepsLabel;
    private JTextField setNumberOfStepsText;
    private JLabel buildModeLabel;
    private ButtonGroup hexModeGroup;
    private ButtonGroup searchModeGroup;
    
    
    
    public OptionsPanel() {
        //construct components
        setStartButton 				= new JRadioButton ("Set Start");
        setWallsButton 				= new JRadioButton ("Design Walls");
        setEndButton 				= new JRadioButton ("Set End");
        searchAlgLabel 				= new JLabel ("Search Algorithims");
        aStarSearchButton 			= new JRadioButton ("A*");
        breadthFirstSearchButton 	= new JRadioButton ("Breadth First");
        greedySearchButton 			= new JRadioButton ("Greedy First");
        doStepButton 				= new JButton ("Step");
        doPlayButton 				= new JButton ("Play");
        doResetButton 				= new JButton ("Reset");
        numberOfStepsLabel 			= new JLabel ("# of Steps");
        setNumberOfStepsText 		= new JTextField (1);
        buildModeLabel 				= new JLabel ("Build Mode");
        hexModeGroup				= new ButtonGroup();
        searchModeGroup				= new ButtonGroup();
        
        hexModeGroup.add(setStartButton);
        hexModeGroup.add(setEndButton);
        hexModeGroup.add(setWallsButton);
        searchModeGroup.add(aStarSearchButton);
        searchModeGroup.add(breadthFirstSearchButton);
        searchModeGroup.add(greedySearchButton);
        

        //set components properties
        doResetButton.setToolTipText ("Reset grid to default state");

        //adjust size and set layout
        setPreferredSize (new Dimension (250, 800));
        setLayout (null);

        //add components
        add (setStartButton);
        add (setWallsButton);
        add (setEndButton);
        add (searchAlgLabel);
        add (aStarSearchButton);
        add (breadthFirstSearchButton);
        add (greedySearchButton);
        add (doStepButton);
        add (doPlayButton);
        add (doResetButton);
        add (numberOfStepsLabel);
        add (setNumberOfStepsText);
        add (buildModeLabel);

        //set component bounds
        setStartButton.setBounds 			(80, 100, 100, 25);
        setWallsButton.setBounds 			(80, 220, 100, 25);
        setEndButton.setBounds 				(80, 160, 100, 25);
        searchAlgLabel.setBounds 			(70, 340, 130, 25);
        aStarSearchButton.setBounds 		(80, 400, 55, 25);
        breadthFirstSearchButton.setBounds 	(80, 460, 100, 25);
        greedySearchButton.setBounds 		(80, 520, 100, 25);
        doStepButton.setBounds 				(10, 645, 75, 25);
        doPlayButton.setBounds 				(150, 645, 75, 25);
        doResetButton.setBounds 			(75, 715, 100, 25);
        numberOfStepsLabel.setBounds 		(95, 670, 60, 25);
        setNumberOfStepsText.setBounds 		(95, 645, 50, 25);
        buildModeLabel.setBounds 			(85, 40, 65, 25);
        
        //Default number of steps
        setNumberOfStepsText.setText( "1" );
        
        //Default mode
        setStartButton.setSelected( true );
        aStarSearchButton.setSelected( true );
        
        setStartButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				//Switch to root/start mode
				HexPrimary.currentMode = HexPrimary.MODE_ROOT;
				
			}
		});
        
        setWallsButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				//Switch to wall mode
				HexPrimary.currentMode = HexPrimary.MODE_WALL;
				
			}
		});
        
        setEndButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				//Switch to goal/end mode
				HexPrimary.currentMode = HexPrimary.MODE_GOAL;
				
			}
		});
        
        aStarSearchButton.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				
				HexPrimary.currentSearch = new AStarSearch();
				HexPrimary.clearNonWalls();
			}
		});
        
        breadthFirstSearchButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				HexPrimary.currentSearch = new BreadthFirstSearch();
				HexPrimary.clearNonWalls();
			}
		});
        
        greedySearchButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				HexPrimary.currentSearch = new GreedySearch();
				HexPrimary.clearNonWalls();
			}
		});
        
        doStepButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				if( HexPrimary.root == null || HexPrimary.goal == null ){
					System.out.println( "Cannot path.  Goal or root not set" );
					return;
				}
				
				if( HexPrimary.currentSearch.foundGoal ){
					System.out.println( "Cannot path.  Goal already found" );
					return;
				}
				
				for (int i = 0; i < Integer.parseInt( setNumberOfStepsText.getText() ); i++) {
					HexPrimary.currentSearch.step();
				}
				
			}
		});
        
        doPlayButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				if( HexPrimary.root == null || HexPrimary.goal == null ){
					System.out.println( "Cannot path.  Goal or root not set" );
					return;
				}
				
				if( HexPrimary.currentSearch.foundGoal ){
					System.out.println( "Cannot path.  Goal already found" );
					return;
				}
				
				HexPrimary.currentSearch.search();
				HexPrimary.hexPanel.repaint();
				
			}
		});
        
        doResetButton.addActionListener(new ActionListener() {
			
			public void actionPerformed(ActionEvent e) {
				
				try {
					HexPrimary.setupGrid();
				} catch (InstantiationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IllegalAccessException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
			}
		});
        
        
    }


}
